export const blockStyles = {
  title: {
    fontSize: "1.8rem",
    fontWeight: "bold",
    textAlign: "left" as const,
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    color: "#000000",
  },
  paragraph: {
    fontSize: "1rem",
    lineHeight: "1.5",
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
    color: "#000000",
  },
  image: {
    display: "block",
    border: "1px solid #ccc",
    borderRadius: "6px",
    maxWidth: "100%",
  },
  button: {
    backgroundColor: "#007bff",
    border: "none",
    color: "#ffffff",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: 500,
    fontSize: "0.95rem",
    transition: "background 0.2s",
    textAlign: "center" as const,
    padding: "8px 16px",
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
  link: {
    color: "#007bff",
    textDecoration: "underline",
    cursor: "pointer",
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
  divider: {
    border: "none",
    borderTop: "2px solid #ccc",
    width: "90%",
  },
  dividerWrapper: {
    width: "100%",
    minWidth: "50px",
    height: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  container: {
    border: "1px solid #999",
    borderRadius: "6px",
    backgroundColor: "#f7f8fa",
    minHeight: "50px",
    minWidth: "50px",
  },
  gridColumn: {
    border: "1px solid #ccc",
    borderRadius: "6px",
    height: "50px",
    backgroundColor: "#fafafa",
  },
  editableBlock: {
    cursor: "text",
    width: "100%",
    height: "100%",
    display: "block",
    fontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
};
